openapi: 3.0.0
info:
  title: Clients REST API
  version: "1.0"
servers:
  - url: http://localhost
paths:
  /users:
    post:
      operationId: userPOST
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/User"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        '5XX':
          description: Server Error

components:
  schemas:
    User:
      type: object
      required:
        - name
      properties:
        userId:
          type: string
        name:
          type: string
